### ISSUE TITLE
implement libabigail check

### ISSUE THREAD

**Issue by phracek** [phracek/rebase-helper#111]
Rebase-helper should implement libabigail check so that users see ABI changes between RPM packages.

**Comment by phracek** [comment]
https://sourceware.org/libabigail/manual/abipkgdiff.html

**Comment by phracek** [comment]
Duplicate of #101

**Comment by dodjiseketeli** [comment]
So, the abipkgdiff tool is now available in a Rawhide and Fedora 22 (among others).  The Fedora 22 package is available at http://koji.fedoraproject.org/koji/buildinfo?buildID=670154 and should hit a mirror near you soon.

Cheers.

**Comment by dodjiseketeli** [comment]
Here is an example of usage for that abipkgdiff tool on the glib-dbus package:

dodji@adjoa:test-diff-pkg$ abipkgdiff --d1 dbus-glib-debuginfo-0.80-3.fc12.x86_64.rpm --d2 dbus-glib-debuginfo-0.104-3.fc23.x86_64.rpm dbus-glib-0.80-3.fc12.x86_64.rpm dbus-glib-0.104-3.fc23.x86_64.rpm
================ changes of 'dbus-binding-tool'===============
  Functions changes summary: 2 Removed, 0 Changed, 0 Added functions
  Variables changes summary: 0 Removed, 0 Changed, 0 Added variable
  Function symbols changes summary: 0 Removed, 1 Added function symbol not referenced by debug info
  Variable symbols changes summary: 0 Removed, 0 Added variable symbol not referenced by debug info

  2 Removed functions:

    'function BaseInfo* base_info_ref(BaseInfo*)'
    'function void base_info_unref(BaseInfo*)'


  1 Added function symbol not referenced by debug info:

    dbus_g_value_build_g_variant

================ end of changes of 'dbus-binding-tool'===============

================ changes of 'libdbus-glib-1.so.2.1.0'===============
  Functions changes summary: 0 Removed, 0 Changed, 0 Added function
  Variables changes summary: 0 Removed, 0 Changed, 0 Added variable
  Function symbols changes summary: 0 Removed, 8 Added function symbols not referenced by debug info
  Variable symbols changes summary: 0 Removed, 0 Added variable symbol not referenced by debug info

  8 Added function symbols not referenced by debug info:

    dbus_g_bus_get_private
    dbus_g_connection_open_private
    dbus_g_connection_unregister_g_object
    dbus_g_method_invocation_get_g_connection
    dbus_g_object_type_register_shadow_property
    dbus_g_value_build_g_variant
    dbus_g_value_parse_g_variant
    dbus_glib_global_set_disable_legacy_property_access

================ end of changes of 'libdbus-glib-1.so.2.1.0'===============

dodji@adjoa:test-diff-pkg$

**Comment by phracek** [comment]
Awesome example. I will keep you infomed.
