### ISSUE TITLE
Csmock as a checker

### ISSUE THREAD

**Issue by phracek** [phracek/rebase-helper#147]
I would like to discuss if covscan does make sense to be a checker in rebase-helper.

@kdudka: Is it already covscan packaged in Fedora?
How to use it? Do you have a documentation for it?

**Comment by kdudka** [comment]
If you want to make sure that a rebase has not introduced any new defects, I would suggest to use csbuild. It is available in Fedora and a brief tutorial on how to use it can be found here:

https://kdudka.fedorapeople.org/devconf15.pdf

**Comment by phracek** [comment]
This is close by PR #205
