### ISSUE TITLE
tox usage for rebase-helper test

### ISSUE THREAD

**Issue by phracek** [phracek/rebase-helper#153]
On the base of discussion with @thozza we could switch our tests to tox.

Is there any volunteer who can handle it?

**Comment by phracek** [comment]
@thozza Could you please describe it a bit more. We have already tox.ini. https://github.com/phracek/rebase-helper/blob/master/tox.ini

**Comment by thozza** [comment]
@phracek I can't, because I don't remember what exactly we discussed. I think I mentioned only that TOX is good for running tests in the same environment locally or in CI.

**Comment by phracek** [comment]
Closing issue for now.
