### ISSUE TITLE
Inconsistent output after unsuccessful merge

### ISSUE THREAD

**Issue by msehnout** [phracek/rebase-helper#157]
rebase-helper seems to ask the same question twice and every time in different way (types of brackets, default option)

    Normal merge conflict for 'tunables.c':
      {local}: modified file
      {remote}: modified file
    tunables.c seems unchanged.
    Was the merge successful? [y/n] n
    merge of tunables.c failed
    Continue merging other unresolved paths (y/n) ? n
    Following files were modified: parseconf.c,ssl.c,tunables.c,tunables.h,vsftpd.conf.5
    Do you want to continue with another patch ([y]/n)? n

**Comment by nforro** [comment]
It's not the same question.
One patch can introduce conflicts in multiple files, mergetool is run for each of them, and if merging fails, git asks if it should continue with the next file, or just skip the patch. That's the "Continue merging other unresolved paths" question.
When the patch is processed, successfully or not, rebase-helper asks if it should proceed to the next patch. That's the "Do you want to continue with another patch" question.

That being said, I agree the form of the questions should be made consistent.

**Comment by nforro** [comment]
The form of the questions asked by git is made consistent in this upstream commit:
https://github.com/git/git/commit/bea99abdb628cf7a42b7cc85eb4e5c5f4e80c7c0

The form of the questions asked by rebase-helper is fixed in 59d2a6331d5179aee73c6cd89998216cd1b30ce6.
