### ISSUE TITLE
Allow to prepare SourceX tarballs

### ISSUE THREAD

**Issue by voxik** [phracek/rebase-helper#161]
There are packages which ships additional sources, rubygem-sprocets for example [1]. Since these sources are not update by rebase helper, the help can't ever succeed [2]. It would be nice, if there is some way, how to allow rebase helper to update the sources. There are two possible scenarios which comes to my mind:

1. If there is Source1 specified in the .spec file and the dist git contains Source1.sh, this scrip would be used to create the associated tarball.

2. It might be also possible to interpret the comment in the source code. For example the rubygem-sprockets contains following lines above the Source1 tag:
 
 ```
 # to get tests:
 # git clone https://github.com/rails/sprockets.git && cd sprockets/
 # git checkout v3.2.0 && tar czf sprockets-3.2.0-tests.tgz test/
 Source1: sprockets-%{version}-tests.tgz
 ```
 
 If there was the # stripped (and the firs line updated such as s/#/# #/), it would be precisely what needs to be done to get the updated tarball.

Not 100% sure rebase helper is the right place. This could be for example part of spectools, but rebase helper could definitely benefit from this.

[1] http://pkgs.fedoraproject.org/cgit/rpms/rubygem-sprockets.git/tree/rubygem-sprockets.spec?id=b4ebd197263b4adffa9e428d657af9bd980b90de#n15
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1260895#c12

**Comment by phracek** [comment]
#145
