### ISSUE TITLE
Problems with copying Sources.

### ISSUE THREAD

**Issue by phracek** [phracek/rebase-helper#164]
Results directory 'rebase-helper-results' exists, removing it
error: failed to load macro file /home/phracek/rpmbuild/SOURCES/macros.preupgrade-assistanterror: File /home/phracek/rpmbuild/SOURCES/preupgrade-assistant-do-not-ship-ui.patch: No such file or directory
error: File /home/phracek/rpmbuild/SOURCES/preupg-fix-print.patch: No such file or directory
error: failed to load macro file /home/phracek/rpmbuild/SOURCES/macros.preupgrade-assistanterror: File /home/phracek/rpmbuild/SOURCES/preupgrade-assistant-do-not-ship-ui.patch: No such file or directory
error: File /home/phracek/rpmbuild/SOURCES/preupg-fix-print.patch: No such file or directory
error: failed to load macro file /home/phracek/rpmbuild/SOURCES/macros.preupgrade-assistanterror: File /home/phracek/rpmbuild/SOURCES/preupgrade-assistant-do-not-ship-ui.patch: No such file or directory
error: File /home/phracek/rpmbuild/SOURCES/preupg-fix-print.patch: No such file or directory
error: failed to load macro file /home/phracek/rpmbuild/SOURCES/macros.preupgrade-assistanterror: File /home/phracek/rpmbuild/SOURCES/preupgrade-assistant-do-not-ship-ui.patch: No such file or directory
error: File /home/phracek/rpmbuild/SOURCES/preupg-fix-print.patch: No such file or directory
error: failed to load macro file /home/phracek/rpmbuild/SOURCES/macros.preupgrade-assistanterror: File /home/phracek/rpmbuild/SOURCES/preupgrade-assistant-do-not-ship-ui.patch: No such file or directory
error: File /home/phracek/rpmbuild/SOURCES/preupg-fix-print.patch: No such file or directory
error: failed to load macro file /home/phracek/rpmbuild/SOURCES/macros.preupgrade-assistanterror: File /home/phracek/rpmbuild/SOURCES/preupgrade-assistant-do-not-ship-ui.patch: No such file or directory
error: File /home/phracek/rpmbuild/SOURCES/preupg-fix-print.patch: No such file or directory
error: failed to load macro file /home/phracek/rpmbuild/SOURCES/macros.preupgrade-assistanterror: File /home/phracek/rpmbuild/SOURCES/preupgrade-assistant-do-not-ship-ui.patch: No such file or directory
error: File /home/phracek/rpmbuild/SOURCES/preupg-fix-print.patch: No such file or directory
error: failed to load macro file /home/phracek/rpmbuild/SOURCES/macros.preupgrade-assistanterror: File /home/phracek/rpmbuild/SOURCES/preupgrade-assistant-do-not-ship-ui.patch: No such file or directory
error: File /home/phracek/rpmbuild/SOURCES/preupg-fix-print.patch: No such file or directory
error: failed to load macro file /home/phracek/rpmbuild/SOURCES/macros.preupgrade-assistanterror: File /home/phracek/rpmbuild/SOURCES/preupgrade-assistant-do-not-ship-ui.patch: No such file or directory
error: File /home/phracek/rpmbuild/SOURCES/preupg-fix-print.patch: No such file or directory
error: failed to load macro file /home/phracek/rpmbuild/SOURCES/macros.preupgrade-assistanterror: File /home/phracek/rpmbuild/SOURCES/preupgrade-assistant-do-not-ship-ui.patch: No such file or directory
error: File /home/phracek/rpmbuild/SOURCES/preupg-fix-print.patch: No such file or directory
error: failed to load macro file /home/phracek/rpmbuild/SOURCES/macros.preupgrade-assistanterror: File /home/phracek/rpmbuild/SOURCES/preupgrade-assistant-do-not-ship-ui.patch: No such file or directory
error: File /home/phracek/rpmbuild/SOURCES/preupg-fix-print.patch: No such file or directory
error: failed to load macro file /home/phracek/rpmbuild/SOURCES/macros.preupgrade-assistanterror: File /home/phracek/rpmbuild/SOURCES/preupgrade-assistant-do-not-ship-ui.patch: No such file or directory
error: File /home/phracek/rpmbuild/SOURCES/preupg-fix-print.patch: No such file or directory

**Comment by nforro** [comment]
Fixed in 09ff96d75ed7821bbfbba70377d3f59ad4ce6811.
