### ISSUE TITLE
See logs and attachments in this bugzilla 'NoneType' object has no attribute 'get_rebasehelper_data'

### ISSUE THREAD

**Issue by praiskup** [phracek/rebase-helper#170]
See:
https://bugzilla.redhat.com/show_bug.cgi?id=1330345

**Comment by phracek** [comment]
I guess, it was fixed in version 0.7.3, but I will clarify it.
@ralphbean: What rebase-helper version do we have installed on production machine?

**Comment by ralphbean** [comment]
0.7.2.  We need to coordinate pushing out an update there.

**Comment by phracek** [comment]
Fixed in the-new-hotness and production machine.
