### ISSUE TITLE
Loggin version into debug log

### ISSUE THREAD

**Issue by phracek** [phracek/rebase-helper#181]
Many times, builds fail from the-new-hotness daemon
and the-new-hotness attaches a rebase-helper debug log.
But we don't know what version of rebase-helper was used for rebasing.

I think, it makes sense to add, at the beginning of log file, version of rebase-helper which is used on a system.

What do you think about it?

**Comment by nforro** [comment]
Yes, that's definitely a good idea.

Speaking of failed builds, I noticed that when SRPM build fails, only rebase-helper debug log is attached to bugzilla. It would be nice to get also log from rpmbuild.

**Comment by phracek** [comment]
Yeah, definitely. rebase-helper has to attach all logs. Even in case of success.
