### ISSUE TITLE
All meld tabs should have names

### ISSUE THREAD

**Issue by mihlit** [phracek/rebase-helper#58]
Right now, only first tab has names "[old_sources]" and "[new_sources]"
The other tabs have no names and it's difficult to find out what is where. Even after ten minutes work I have to focus hard what tab has what content. Old vanilla/new vanilla/old patched/new patched.

**Comment by phracek** [comment]
We change the patching process from patch command to git rebase. Therefore it depends how do you have setup your ~/.gitconfig command.
