### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by phracek** [phracek/rebase-helper#75]
ChangeLog section should be updated if everything goes fine.

User who execute rebase-helper either specify username and email or
it will be taken from previous log. Except mass rebuild stuff.

**Comment by phracek** [comment]
rpmdev-bumpspec <name>.spec -n <version> -c 'Comments updated change'

I have discovered that if -n is specified like 3.14.0b1 then version is updated correctly.
I think that it solves our problems with complicated tarball versions.

**Comment by thozza** [comment]
No, it is not updated correctly. The 'extra version' is supposed to be included in the Release *NOT* the Version. Also extraction of version and extra version in complicated tarballs is already solved, there are other thing that need to be solved, like the %setup macro for cases with extra version.

It may work, however this does NOT conform to the Fedora packaging guidelines:
https://fedoraproject.org/wiki/Packaging:NamingGuidelines#Version_Tag
