### ISSUE TITLE
Try to rebuild dependent packages in some situations, like SO name version bump

### ISSUE THREAD

**Issue by thozza** [phracek/rebase-helper#85]
If package distributes versioned shared libraries, the update to latest upstream version may cause the library version to be bumped. The new library version may not be compatible with the previous one, thus making the dependent packages rebuild to fail.

In such situation it would be useful if rebase-helper would try to rebuild dependent packages against the RPMs build from the new sources.

Of course this should happen only if the new RPM packages build successfully.

**Comment by phracek** [comment]
I guess, this is related to koschei. #173
