### ISSUE TITLE
don't open meld when there is no conflict at all

### ISSUE THREAD

**Issue by pavlix** [phracek/rebase-helper#89]
When rebasing a package with lots of patches already applied upstream, the third meld tab often shows that the files are identical or at least doesn't show any conflicting changes. I need to confirm all the individual files and then the patch itself even though there's no work to do on my side at all.

**Comment by thozza** [comment]
This will be hopefully resolved by switching to 'git rebase' workflow. Petr is currently working on it. I'll ask you to retest once it is merged to the master. Thanks!

**Comment by phracek** [comment]
Could you please give me a package name on which I can test it?
THX

**Comment by phracek** [comment]
This issue is solved by git rebase. Already included in master branch
